# ACI playbook - Demo 07 - Ansible Roles
---
- hosts: apic
  connection: local
  gather_facts: no
  # roles:
  #   - role: aci-network-noseg
  #     network_name: vlan001
  #     network_type: L3
  #     subnet: 192.168.1.1/24
  #     public: yes

  vars:
    tenant_name: development_tn
    vrf_name: dev_vrf
    app_name: app_demo_ap
    aci_login: &aci_login
      host: "{{ ansible_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password | default(omit) }}"
      private_key: "{{ aci_private_key | default(omit) }}"
      certificate_name: "{{ aci_certificate_name | default(omit) }}"
      validate_certs: "{{ aci_validate_certs }}"

  tasks:
    - name: Add Development Tenant
      cisco.aci.aci_tenant:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        state: present

    - name: Add Development VRF
      cisco.aci.aci_vrf:
        <<: *aci_login
        vrf: "{{ vrf_name }}"
        tenant: "{{ tenant_name }}"
        policy_control_preference: enforced
        policy_control_direction: ingress
        state: present

    - name: Add Application Profile
      cisco.aci.aci_ap:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ app_name }}"
        state: present

    - name: Add network
      include_role:
        name: aci-network-noseg
      vars:
        network_name: vlan001
        network_type: L3
        subnet: 192.168.1.1/24
        public: yes
